src/main.js, src/main.ts
alert "hello" when code block is clicked.
Close #2
Code block is a "View Code" view of a file(*.pu, *.puml, *plantuml) or a comment, whose language is pu, uml or puml like as folows: 
```pu
@startuml Domain Model
title ドメインモデル
left to right direction
class "User（ユーザ）" as User {
username（ユーザ名） : string
email（メールアドレス） : string
password（パスワード） : string
createdAt（アカウント作成日時） : Date
}
class "Organization（組織）" as Organization
interface "Role（ロール）" as Role
class "Learner（学習者）" as Learner
class "Admin（管理者）" as Admin
class "Manager（マネージャー）" as Manager
class "Teacher（教師）" as Teacher
class "Subject（科目）" as Subject
class "Workbook（問題集）" as Workbook
class "Question（問題）" as Question {
id（ID） : string
key（キー） : string
sentence（問題文） : string
commentary（解説） : string
answer（正答） : string
}
class …
```
=> feat: alert "hello" when code block is clicked

.idea/misc.xml, package.json, src/PlantUmlEncoder.ts, src/main.ts, src/popup.ts, yarn.lock
=> feat: add encoder converting UML text into image URL

README.md, manifest.json, package.json, src/Finder.ts, src/Mutator.ts, src/PlantUmlEncoder.ts, src/background.ts, src/content_scripts.ts, yarn.lock
=> feat: embed PlantUML images when DOM changes

src/content_scripts.ts
=> fix: analyze whole document when some nodes are added

src/background.ts
=> feat: show off badge when the extension is disabled

src/Finder.ts, src/GitHubFinder.ts, src/Mutator.ts, src/content_scripts.ts
Add functions for Pull Request diffs.
The functions consist of PlantUmlDiffContent, DiffFinder and DiffMutator (Diff-* family).
close #25
=> feat: add PlantUML diff visualizer

src/Finder.ts, src/GitHubFinder.ts, src/Mutator.ts
=> feat: add branch mark

src/GitHubFinder.ts, src/Mutator.ts
=> fix: treat not found errors

.gitignore
=> build: change gitignore

src/Constants.ts, src/Mutator.ts, src/PlantUmlEncoder.ts, src/background.ts
=> fix: visualize large diagram correctly

src/Mutator.ts
=> fix: prevent cloned image

src/Constants.ts, src/content_scripts.ts
=> fix: judge if MutationOvserver is needed by checking URL

src/Mutator.ts
=> feat: add styles of before/after labels

README.md, manifest.json
=> fix: support file urls correctly

puml-sample/state.pu, puml-sample/substate.pu
This is **NOT** a PR test
Merge me!
=> test: add sample with !include

.vscode/settings.json, src/constants.ts, src/content_scripts.ts, src/finder/finder.ts, src/finder/gitHubFinder.ts, src/finder/rawFileFinder.ts, src/mutator/descriptionMutator.ts, src/mutator/diffMutator.ts, src/mutator/mutatorUtil.ts
=> fix: don't find elements embedded by mutators

README.md, manifest.json, puml-sample/sequence.wsd, src/finder/gitHubFinder.ts
=> feat: support *.wsd extension

.vscode/settings.json, manifest.json, package.json, rollup.config.js, src/background.ts, src/constants.ts, src/content_scripts.ts, src/encoder/plantUmlEncoder.ts, src/finder/gitHubFinder.ts, src/mutator/mutatorUtil.ts, src/popup.html, src/popup.ts, yarn.lock
- Add configuration popup
- Toggle enable/disable
- Url of PlantUML server (close #502)
- Store configuration values in local storage (close #552)
- Validate url of PlantUML server (close #550)
=> feat: implement configuration popup

src/finder/codeBlockFinder.ts
=> fix: mutate only <pre> which has @startuml prefix and @enduml suffix

src/content_scripts.ts, src/finder/codeBlockFinder.ts, src/finder/gitHubFinder.ts
=> fix: disable any mutation on GitHub editor

src/directiveRegexes.ts, src/finder/codeBlockFinder.ts, src/finder/finderUtil.ts, src/finder/gitHubFinder.ts, src/regexes.ts
=> fix: ignore case sensitivity for finding directives

.eslintrc.js
=> chore: disable ESLint for SCSS on Svelte

src/components/BodyContainer.svelte, src/components/Button.svelte, src/components/Footer.svelte, src/components/Header.svelte, src/components/ItemContainer.svelte, src/components/ItemLabel.svelte, src/components/Switch.svelte, src/components/TextField.svelte, src/popup.svelte
close #551
| Current | Incoming |
|-|-|
| <img width="400" src="https://user-images.githubusercontent.com/9990535/113364706-2678f600-938f-11eb-93e3-a912f28ddb80.png"> | <img width="400" src="https://user-images.githubusercontent.com/9990535/113364618-f03b7680-938e-11eb-9526-46da407291c7.png"> |
=> feat: improve the styling of the popup

README.md, manifest.json, src/constants.ts, src/content_scripts.ts, src/popup.svelte
=> fix: don’t apply visualization in unexpected webpages

manifest.json
It is convenient for me to show UMLs in gist too.
=> feat: add gist to allowed URLs

.github/workflows/semantic-release.yml, README.md
=> build: implement scheduled release

src/background.ts, src/components/Footer.svelte, src/config.ts, src/constants.ts, src/content_scripts.ts, src/popup.svelte
=> feat: support allow list
